task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      # image: freebsd-11-4-release-amd64
      # image: freebsd-12-2-release-amd64
      image: freebsd-13-2-release-amd64
  install_script:
    - pkg info
    - pkg install -y gcc
    - pkg install -y perl5
    - perl -V
    - pkg install -y p5-App-cpanminus
    - cpanm --installdeps .
  build_script:
    - perl Makefile.PL
  test_script:
    - make test

