---
abstract: 'Low-Level Interface to bzip2 compression library'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compress-Raw-Bzip2
no_index:
  directory:
    - t
    - inc
    - t
    - private
resources:
  bugtracker: https://github.com/pmqs/Compress-Raw-Bzip2/issues
  homepage: https://github.com/pmqs/Compress-Raw-Bzip2
  repository: git://github.com/pmqs/Compress-Raw-Bzip2.git
version: '2.214'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
